/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiV1RouteImport } from './routes/api/v1'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard.agents'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard.discover'
import { Route as DashboardKeysRouteImport } from './routes/dashboard.keys'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as DashboardAgentsIndexRouteImport } from './routes/dashboard.agents.index'
import { Route as DashboardAgentsAgentIdRouteImport } from './routes/dashboard.agents.$agentId'
import { Route as DashboardAgentsNewRouteImport } from './routes/dashboard.agents.new'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/dashboard.tasks.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1Route = ApiV1RouteImport.update({
  id: '/api/v1',
  path: '/api/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiV1Route,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardAgentsAgentIdRoute = DashboardAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardAgentsNewRoute = DashboardAgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => DashboardTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdRoute
  '/dashboard/agents/new': typeof DashboardAgentsNewRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdRoute
  '/dashboard/agents/new': typeof DashboardAgentsNewRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/agents': typeof DashboardAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/users': typeof AdminUsersRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/api/health': typeof ApiHealthRoute
  '/api/v1': typeof ApiV1RouteWithChildren
  '/dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/dashboard/usage': typeof DashboardUsageRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/dashboard/agents/$agentId': typeof DashboardAgentsAgentIdRoute
  '/dashboard/agents/new': typeof DashboardAgentsNewRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/directory'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/admin/agents'
    | '/admin/logs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/agents/$agentId'
    | '/api/health'
    | '/api/v1'
    | '/dashboard/agents'
    | '/dashboard/billing'
    | '/dashboard/discover'
    | '/dashboard/keys'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/usage'
    | '/admin/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/dashboard/agents/$agentId'
    | '/dashboard/agents/new'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/directory'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/admin/agents'
    | '/admin/logs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/agents/$agentId'
    | '/api/health'
    | '/api/v1'
    | '/dashboard/billing'
    | '/dashboard/discover'
    | '/dashboard/keys'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/usage'
    | '/admin'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/dashboard/agents/$agentId'
    | '/dashboard/agents/new'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/agents'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/directory'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/admin/agents'
    | '/admin/logs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/agents/$agentId'
    | '/api/health'
    | '/api/v1'
    | '/dashboard/agents'
    | '/dashboard/billing'
    | '/dashboard/discover'
    | '/dashboard/keys'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/usage'
    | '/admin/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/dashboard/agents/$agentId'
    | '/dashboard/agents/new'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiV1Route: typeof ApiV1RouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1': {
      id: '/api/v1'
      path: '/api/v1'
      fullPath: '/api/v1'
      preLoaderRoute: typeof ApiV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof ApiV1Route
    }
    '/dashboard/agents/': {
      id: '/dashboard/agents/'
      path: '/'
      fullPath: '/dashboard/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/dashboard/agents/$agentId': {
      id: '/dashboard/agents/$agentId'
      path: '/$agentId'
      fullPath: '/dashboard/agents/$agentId'
      preLoaderRoute: typeof DashboardAgentsAgentIdRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/dashboard/agents/new': {
      id: '/dashboard/agents/new'
      path: '/new'
      fullPath: '/dashboard/agents/new'
      preLoaderRoute: typeof DashboardAgentsNewRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/dashboard/tasks/$taskId': {
      id: '/dashboard/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardTasksRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardAgentsRouteChildren {
  DashboardAgentsAgentIdRoute: typeof DashboardAgentsAgentIdRoute
  DashboardAgentsNewRoute: typeof DashboardAgentsNewRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
}

const DashboardAgentsRouteChildren: DashboardAgentsRouteChildren = {
  DashboardAgentsAgentIdRoute: DashboardAgentsAgentIdRoute,
  DashboardAgentsNewRoute: DashboardAgentsNewRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
}

const DashboardAgentsRouteWithChildren = DashboardAgentsRoute._addFileChildren(
  DashboardAgentsRouteChildren,
)

interface DashboardTasksRouteChildren {
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
}

const DashboardTasksRouteChildren: DashboardTasksRouteChildren = {
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
}

const DashboardTasksRouteWithChildren = DashboardTasksRoute._addFileChildren(
  DashboardTasksRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRouteWithChildren
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRouteWithChildren,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiV1RouteChildren {
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

const ApiV1RouteChildren: ApiV1RouteChildren = {
  ApiV1SplatRoute: ApiV1SplatRoute,
}

const ApiV1RouteWithChildren = ApiV1Route._addFileChildren(ApiV1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiV1Route: ApiV1RouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
